version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    ECR_REPO_URI: 831516339607.dkr.ecr.eu-north-1.amazonaws.com/flask-app
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - docker --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 831516339607.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Running unit tests
      - pip install -r requirements.txt
      - pytest

      - echo Building Docker image
      - docker build -t flask-app:$IMAGE_TAG .
      - docker tag flask-app:$IMAGE_TAG $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push $ECR_REPO_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
